databases:
  - name: online_class_reservation_development
    databaseName: online_class_reservation_development
    user: lydia


services:
  - type: web
    name: online_class_reservation_development
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysite
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2