
default: &default
  adapter: postgresql
  encoding: unicode
  host: ''
  password: 'ingabire'
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: online_class_reservation_development

test:
  <<: *default
  database: online_class_reservation

production:
  <<: *default
  database: online_class_reservation_production
  username: online_class_reservation
  password: <%= ENV['ONLINE_CLASS_RESERVATION_DATABASE_PASSWORD'] %>