default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DB_HOST'] %>
  port: 5432
  username: <%= ENV['DB_USERNAME'] %> 
  password: <%= ENV['DB_PASSWORD'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: online_class_reservation_development

test:
  <<: *default
  database: online_class_reservation_test

production:
  <<: *default
  database: <%= ENV['DB_NAME'] %>
